/**
 * AdHub YouTube Downloader v5.5 - Background Script
 *
 * Hybridni rezim:
 * - Zakladni: Prime stahovani pres chrome.downloads (max 720p)
 * - Rozsireny: Native Messaging s yt-dlp/ffmpeg (vse)
 *
 * Nove v5.5:
 * - Automaticke ziskavani cookies pro vekove omezena videa
 */

console.log('[AdHub BG] YouTube Downloader v5.5 (Hybrid) loaded');

// ============================================================================
// KONFIGURACE
// ============================================================================

const NATIVE_HOST = 'com.adhub.ytdownloader';
const STORAGE_KEY = 'adhub_yt_settings';

// ============================================================================
// STAV
// ============================================================================

const state = {
  settings: {
    ytdlpPath: '',
    ffmpegPath: '',
    nativeHostInstalled: false
  },
  nativePort: null
};

// ============================================================================
// INIT - Nacti nastaveni pri startu
// ============================================================================

(async function init() {
  try {
    const result = await chrome.storage.local.get(STORAGE_KEY);
    if (result[STORAGE_KEY]) {
      state.settings = { ...state.settings, ...result[STORAGE_KEY] };
      console.log('[AdHub BG] Nastaveni nacteno:', state.settings);
    }
  } catch (e) {
    console.log('[AdHub BG] Chyba pri nacitani nastaveni:', e);
  }
})();

// ============================================================================
// MESSAGE HANDLER
// ============================================================================

chrome.runtime.onMessage.addListener((request, sender, sendResponse) => {
  console.log('[AdHub BG] Message:', request.action);

  switch (request.action) {
    case 'ping':
      sendResponse({ success: true, version: '5.5', mode: 'hybrid' });
      return false;

    case 'download':
      handleDownload(request.data)
        .then(result => sendResponse(result))
        .catch(error => sendResponse({ success: false, error: error.message }));
      return true;

    case 'downloadAdvanced':
      handleAdvancedDownload(request.data)
        .then(result => sendResponse(result))
        .catch(error => sendResponse({ success: false, error: error.message }));
      return true;

    case 'checkNativeHost':
      checkNativeHost()
        .then(result => sendResponse(result))
        .catch(error => sendResponse({ nativeHostAvailable: false, error: error.message }));
      return true;

    case 'testTool':
      testTool(request.tool, request.path)
        .then(result => sendResponse(result))
        .catch(error => sendResponse({ success: false, error: error.message }));
      return true;

    case 'updateSettings':
      state.settings = { ...state.settings, ...request.settings };
      console.log('[AdHub BG] Nastaveni aktualizovano:', state.settings);
      sendResponse({ success: true });
      return false;

    case 'getSettings':
      sendResponse({ success: true, settings: state.settings });
      return false;

    case 'generateInstaller':
      sendResponse(handleGenerateInstaller(request.platform));
      return false;

    default:
      sendResponse({ success: false, error: 'Unknown action' });
      return false;
  }
});

// ============================================================================
// COOKIES - Automaticke ziskavani pro vekove omezena videa
// ============================================================================

async function getYouTubeCookies() {
  try {
    // Ziskat vsechny YouTube cookies (vcetne YouTube Music)
    const cookies = await chrome.cookies.getAll({ domain: '.youtube.com' });
    const musicCookies = await chrome.cookies.getAll({ domain: 'music.youtube.com' });
    const googleCookies = await chrome.cookies.getAll({ domain: '.google.com' });

    const allCookies = [...cookies, ...musicCookies, ...googleCookies];

    if (allCookies.length === 0) {
      console.log('[AdHub BG] Zadne YouTube cookies nenalezeny');
      return null;
    }

    // Konvertovat na Netscape format (pro yt-dlp)
    const netscapeCookies = allCookies.map(cookie => {
      const domain = cookie.domain.startsWith('.') ? cookie.domain : '.' + cookie.domain;
      const flag = cookie.domain.startsWith('.') ? 'TRUE' : 'FALSE';
      const path = cookie.path || '/';
      const secure = cookie.secure ? 'TRUE' : 'FALSE';
      const expires = cookie.expirationDate ? Math.floor(cookie.expirationDate) : 0;
      const name = cookie.name;
      const value = cookie.value;

      return `${domain}\t${flag}\t${path}\t${secure}\t${expires}\t${name}\t${value}`;
    });

    // Pridat hlavicku Netscape formatu
    const cookieFile = [
      '# Netscape HTTP Cookie File',
      '# https://curl.haxx.se/docs/http-cookies.html',
      '# This file was generated by AdHub YouTube Downloader',
      '',
      ...netscapeCookies
    ].join('\n');

    console.log('[AdHub BG] Ziskano', allCookies.length, 'cookies');
    return cookieFile;

  } catch (e) {
    console.error('[AdHub BG] Chyba pri ziskavani cookies:', e);
    return null;
  }
}

// ============================================================================
// ZAKLADNI STAHOVANI (Prime URL pres chrome.downloads)
// ============================================================================

async function handleDownload(data) {
  const { url, filename } = data;

  if (!url) {
    throw new Error('URL is required');
  }

  console.log('[AdHub BG] Starting basic download:', filename);

  return new Promise((resolve, reject) => {
    chrome.downloads.download({
      url: url,
      filename: filename || 'video.mp4',
      saveAs: false,
      conflictAction: 'uniquify'
    }, (downloadId) => {
      if (chrome.runtime.lastError) {
        console.error('[AdHub BG] Download error:', chrome.runtime.lastError.message);
        reject(new Error(chrome.runtime.lastError.message));
      } else if (downloadId === undefined) {
        reject(new Error('Download failed to start'));
      } else {
        console.log('[AdHub BG] Download started, ID:', downloadId);
        resolve({ success: true, downloadId: downloadId });
      }
    });
  });
}

// ============================================================================
// ROZSIRENE STAHOVANI (pres Native Host s yt-dlp)
// ============================================================================

async function handleAdvancedDownload(data) {
  const { videoUrl, format, quality, audioFormat } = data;

  if (!videoUrl) {
    throw new Error('Video URL is required');
  }

  console.log('[AdHub BG] Starting advanced download via native host');

  // Automaticky ziskat cookies
  const cookies = await getYouTubeCookies();

  return sendNativeMessage({
    action: 'download',
    url: videoUrl,
    format: format || 'mp4',
    quality: quality || 'best',
    audioFormat: audioFormat,
    ytdlpPath: state.settings.ytdlpPath,
    ffmpegPath: state.settings.ffmpegPath,
    cookies: cookies,  // Poslat cookies na native host
    useCookies: true
  });
}

// ============================================================================
// NATIVE MESSAGING
// ============================================================================

function connectNativeHost() {
  if (state.nativePort) {
    return state.nativePort;
  }

  try {
    state.nativePort = chrome.runtime.connectNative(NATIVE_HOST);

    state.nativePort.onDisconnect.addListener(() => {
      console.log('[AdHub BG] Native host disconnected');
      state.nativePort = null;
    });

    console.log('[AdHub BG] Connected to native host');
    return state.nativePort;

  } catch (e) {
    console.error('[AdHub BG] Failed to connect native host:', e);
    state.nativePort = null;
    throw e;
  }
}

async function sendNativeMessage(message) {
  return new Promise((resolve, reject) => {
    try {
      chrome.runtime.sendNativeMessage(NATIVE_HOST, message, (response) => {
        if (chrome.runtime.lastError) {
          console.error('[AdHub BG] Native message error:', chrome.runtime.lastError.message);
          reject(new Error(chrome.runtime.lastError.message));
        } else if (response?.error) {
          reject(new Error(response.error));
        } else {
          resolve(response);
        }
      });
    } catch (e) {
      reject(e);
    }
  });
}

async function checkNativeHost() {
  try {
    const response = await sendNativeMessage({
      action: 'check',
      ytdlpPath: state.settings.ytdlpPath,
      ffmpegPath: state.settings.ffmpegPath
    });

    return {
      nativeHostAvailable: true,
      ytdlpAvailable: response.ytdlp?.available || false,
      ytdlpVersion: response.ytdlp?.version || null,
      ffmpegAvailable: response.ffmpeg?.available || false,
      ffmpegVersion: response.ffmpeg?.version || null
    };

  } catch (e) {
    console.log('[AdHub BG] Native host check failed:', e.message);
    return {
      nativeHostAvailable: false,
      error: e.message
    };
  }
}

async function testTool(tool, path) {
  try {
    const response = await sendNativeMessage({
      action: 'test',
      tool: tool,
      path: path
    });

    return {
      success: response.available || false,
      version: response.version || null,
      error: response.error || null
    };

  } catch (e) {
    return {
      success: false,
      error: e.message
    };
  }
}

// ============================================================================
// DOWNLOAD STATUS TRACKING
// ============================================================================

chrome.downloads.onChanged.addListener((delta) => {
  if (delta.state) {
    if (delta.state.current === 'complete') {
      console.log('[AdHub BG] Download completed:', delta.id);
    } else if (delta.state.current === 'interrupted') {
      console.log('[AdHub BG] Download interrupted:', delta.id, delta.error);
    }
  }
});

// ============================================================================
// INSTALATOR - GENEROVANI
// ============================================================================

function generateWindowsInstaller() {
  // Generujeme .bat soubor ktery automaticky spusti PowerShell s bypass
  // Uzivatel jen poklikat na soubor - zadne slozite prikazy
  return `@echo off
chcp 65001 >nul 2>&1
title AdHub YouTube Downloader - Instalator v5.5

echo.
echo ==============================================
echo   AdHub YouTube Downloader - Instalator v5.5
echo ==============================================
echo.
echo Spoustim instalaci...
echo.

:: Vytvorit docasny PowerShell skript a spustit ho
set "PS_SCRIPT=%TEMP%\\adhub_install.ps1"

:: Zapiseme PowerShell skript
(
echo $ErrorActionPreference = 'Stop'
echo $ProgressPreference = 'SilentlyContinue'
echo.
echo Write-Host '[+] Vytvarim slozky...' -ForegroundColor Green
echo $InstallDir = "$env:LOCALAPPDATA\\AdHub"
echo $YtdlpDir = "$InstallDir\\yt-dlp"
echo $FfmpegDir = "$InstallDir\\ffmpeg"
echo $NativeHostDir = "$InstallDir\\native-host"
echo New-Item -ItemType Directory -Force -Path $YtdlpDir ^| Out-Null
echo New-Item -ItemType Directory -Force -Path $FfmpegDir ^| Out-Null
echo New-Item -ItemType Directory -Force -Path $NativeHostDir ^| Out-Null
echo Write-Host "    Cesta: $InstallDir" -ForegroundColor Cyan
echo.
echo Write-Host '[+] Stahuji yt-dlp...' -ForegroundColor Green
echo $YtdlpExe = "$YtdlpDir\\yt-dlp.exe"
echo Invoke-WebRequest -Uri 'https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp.exe' -OutFile $YtdlpExe -UseBasicParsing
echo Write-Host "    OK: $YtdlpExe" -ForegroundColor Cyan
echo.
echo Write-Host '[+] Stahuji ffmpeg...' -ForegroundColor Green
echo Write-Host '    Zdroj: gyan.dev ^(cca 80 MB, prosim cekejte...^)' -ForegroundColor Yellow
echo $FfmpegZip = "$env:TEMP\\ffmpeg.zip"
echo $FfmpegExtract = "$env:TEMP\\ffmpeg-extract"
echo try {
echo     $ffmpegUrl = 'https://www.gyan.dev/ffmpeg/builds/ffmpeg-release-essentials.zip'
echo     [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
echo     $wc = New-Object System.Net.WebClient
echo     $wc.DownloadFile^($ffmpegUrl, $FfmpegZip^)
echo     Write-Host '    Stazeno! Rozbaluji...' -ForegroundColor Green
echo     if ^(Test-Path $FfmpegExtract^) { Remove-Item -Path $FfmpegExtract -Recurse -Force }
echo     Expand-Archive -Path $FfmpegZip -DestinationPath $FfmpegExtract -Force
echo     $bin = Get-ChildItem -Path $FfmpegExtract -Recurse -Directory ^| Where-Object { $_.Name -eq 'bin' } ^| Select-Object -First 1
echo     if ^($bin^) {
echo         Copy-Item -Path "$^($bin.FullName^)\\ffmpeg.exe" -Destination $FfmpegDir -Force
echo         Copy-Item -Path "$^($bin.FullName^)\\ffprobe.exe" -Destination $FfmpegDir -Force -ErrorAction SilentlyContinue
echo         Write-Host "    OK: $FfmpegDir\\ffmpeg.exe" -ForegroundColor Cyan
echo     } else {
echo         Write-Host "    CHYBA: bin slozka nenalezena v archivu" -ForegroundColor Yellow
echo     }
echo     Remove-Item -Path $FfmpegZip -Force -ErrorAction SilentlyContinue
echo     Remove-Item -Path $FfmpegExtract -Recurse -Force -ErrorAction SilentlyContinue
echo } catch {
echo     Write-Host "    CHYBA: $^($_.Exception.Message^)" -ForegroundColor Yellow
echo     Write-Host "    Zkuste stahnout rucne z: https://www.gyan.dev/ffmpeg/builds/" -ForegroundColor Yellow
echo }
echo.
echo Write-Host '[+] Vytvarim Native Host...' -ForegroundColor Green
echo $PyScript = @'
echo #!/usr/bin/env python3
echo import sys,os,json,struct,subprocess,shutil,tempfile,atexit
echo VERSION='5.5'
echo def read_message^(^):
echo     raw=sys.stdin.buffer.read^(4^)
echo     if not raw:return None
echo     return json.loads^(sys.stdin.buffer.read^(struct.unpack^('I',raw^)[0]^).decode^('utf-8'^)^)
echo def send_message^(m^):
echo     e=json.dumps^(m^).encode^('utf-8'^)
echo     sys.stdout.buffer.write^(struct.pack^('I',len^(e^)^)+e^)
echo     sys.stdout.buffer.flush^(^)
echo def find_tool^(n,c=None^):
echo     for p in [c,shutil.which^(n^)]:
echo         if p:
echo             try:
echo                 r=subprocess.run^([p,'--version'],capture_output=True,text=True,timeout=10^)
echo                 if r.returncode==0:return{'available':True,'path':p,'version':'ok'}
echo             except:pass
echo     return{'available':False,'path':None,'version':None}
echo _tcf=None
echo def save_cookies^(c^):
echo     global _tcf
echo     if not c:return None
echo     fd,p=tempfile.mkstemp^(suffix='.txt'^)
echo     with os.fdopen^(fd,'w'^)as f:f.write^(c^)
echo     _tcf=p
echo     return p
echo def cleanup^(^):
echo     if _tcf and os.path.exists^(_tcf^):os.remove^(_tcf^)
echo atexit.register^(cleanup^)
echo def handle_download^(m^):
echo     url,fmt,q,af=m.get^('url'^),m.get^('format','video'^),m.get^('quality','best'^),m.get^('audioFormat'^)
echo     yt=find_tool^('yt-dlp',m.get^('ytdlpPath'^)^)
echo     if not yt['available']:return{'success':False,'error':'yt-dlp neni dostupny'}
echo     cmd=[yt['path'],'--no-playlist','--no-warnings','-o',os.path.expanduser^('~/Downloads/%%^(title^).150s.%%^(ext^)s'^)]
echo     ck=save_cookies^(m.get^('cookies'^)^)
echo     if ck:cmd.extend^(['--cookies',ck]^)
echo     if fmt=='audio'or af:
echo         cmd.extend^(['-f','bestaudio/best']^)
echo         if af:cmd.extend^(['-x','--audio-format',af]^)
echo     else:
echo         cmd.extend^(['-f','bestvideo+bestaudio/best','--merge-output-format','mp4']^)
echo     ff=find_tool^('ffmpeg',m.get^('ffmpegPath'^)^)
echo     if ff['available']:cmd.extend^(['--ffmpeg-location',os.path.dirname^(ff['path']^)]^)
echo     cmd.append^(url^)
echo     try:
echo         r=subprocess.run^(cmd,capture_output=True,text=True,timeout=900^)
echo         return{'success':r.returncode==0,'error':r.stderr[:200]if r.returncode!=0 else None}
echo     except Exception as e:return{'success':False,'error':str^(e^)[:200]}
echo def main^(^):
echo     while True:
echo         m=read_message^(^)
echo         if not m:break
echo         a=m.get^('action'^)
echo         if a=='check':send_message^({'success':True,'version':VERSION,'ytdlp':find_tool^('yt-dlp'^),'ffmpeg':find_tool^('ffmpeg'^)}^)
echo         elif a=='test':send_message^(find_tool^(m.get^('tool'^),m.get^('path'^)^)^)
echo         elif a=='download':send_message^(handle_download^(m^)^);break
echo         elif a=='ping':send_message^({'success':True,'version':VERSION}^)
echo         else:send_message^({'success':False,'error':'Unknown'^)
echo if __name__=='__main__':main^(^)
echo '@
echo Set-Content -Path "$NativeHostDir\\adhub_yt_host.py" -Value $PyScript -Encoding UTF8
echo Write-Host "    OK: $NativeHostDir\\adhub_yt_host.py" -ForegroundColor Cyan
echo.
echo Write-Host '[+] Vytvarim manifest...' -ForegroundColor Green
echo $manifest = @"
echo {
echo   "name": "com.adhub.ytdownloader",
echo   "description": "AdHub YouTube Downloader Native Host",
echo   "path": "$NativeHostDir\\adhub_yt_host.py",
echo   "type": "stdio",
echo   "allowed_origins": ["chrome-extension://*/"]
echo }
echo "@
echo Set-Content -Path "$NativeHostDir\\com.adhub.ytdownloader.json" -Value $manifest -Encoding UTF8
echo.
echo Write-Host '[+] Registruji pro Chrome...' -ForegroundColor Green
echo $regPath = 'HKCU:\\Software\\Google\\Chrome\\NativeMessagingHosts\\com.adhub.ytdownloader'
echo New-Item -Path $regPath -Force ^| Out-Null
echo Set-ItemProperty -Path $regPath -Name '^(Default^)' -Value "$NativeHostDir\\com.adhub.ytdownloader.json"
echo.
echo Write-Host '[+] Registruji pro Edge...' -ForegroundColor Green
echo $regPath = 'HKCU:\\Software\\Microsoft\\Edge\\NativeMessagingHosts\\com.adhub.ytdownloader'
echo New-Item -Path $regPath -Force ^| Out-Null
echo Set-ItemProperty -Path $regPath -Name '^(Default^)' -Value "$NativeHostDir\\com.adhub.ytdownloader.json"
echo.
echo Write-Host ''
echo Write-Host '==============================================' -ForegroundColor Green
echo Write-Host '  INSTALACE DOKONCENA!' -ForegroundColor Green
echo Write-Host '==============================================' -ForegroundColor Green
echo Write-Host ''
echo Write-Host "yt-dlp:  $YtdlpExe" -ForegroundColor Cyan
echo Write-Host "ffmpeg:  $FfmpegDir\\ffmpeg.exe" -ForegroundColor Cyan
echo Write-Host ''
echo Write-Host 'Restartujte prohlizec a otevrete rozsireni.' -ForegroundColor Yellow
) > "%PS_SCRIPT%"

:: Spustit PowerShell skript s bypass
powershell -ExecutionPolicy Bypass -File "%PS_SCRIPT%"

:: Smazat docasny skript
del "%PS_SCRIPT%" 2>nul

echo.
pause
`;
}

function generateUnixInstaller() {
  return `#!/bin/bash
# AdHub YouTube Downloader - Instalator pro Linux/macOS v5.5

set -e
GREEN='\\033[0;32m'; YELLOW='\\033[1;33m'; CYAN='\\033[0;36m'; NC='\\033[0m'

echo ""
echo -e "\${YELLOW}==============================================\${NC}"
echo -e "\${YELLOW}  AdHub YouTube Downloader - Instalator v5.5\${NC}"
echo -e "\${YELLOW}==============================================\${NC}"
echo ""

INSTALL_DIR="$HOME/.local/share/adhub"
mkdir -p "$INSTALL_DIR/bin" "$INSTALL_DIR/native-host"

# yt-dlp
echo -e "\${GREEN}[+]\${NC} Stahuji yt-dlp..."
YTDLP="$INSTALL_DIR/bin/yt-dlp"
if [[ "$(uname)" == "Darwin" ]]; then
    curl -L -o "$YTDLP" "https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp_macos"
else
    curl -L -o "$YTDLP" "https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp"
fi
chmod +x "$YTDLP"
echo -e "    \${CYAN}$YTDLP\${NC}"

# ffmpeg check
FFMPEG_PATH=""
if command -v ffmpeg &> /dev/null; then
    FFMPEG_PATH=$(which ffmpeg)
    echo -e "\${GREEN}[+]\${NC} ffmpeg nalezen: \${CYAN}$FFMPEG_PATH\${NC}"
else
    echo -e "\${YELLOW}[!]\${NC} ffmpeg neni nainstalovan"
    if [[ "$(uname)" == "Darwin" ]]; then
        echo "    Nainstalujte: brew install ffmpeg"
    else
        echo "    Nainstalujte: sudo apt install ffmpeg"
    fi
fi

# Native Host
echo -e "\${GREEN}[+]\${NC} Vytvarim Native Host..."
cat > "$INSTALL_DIR/native-host/adhub_yt_host.py" << 'PYEOF'
#!/usr/bin/env python3
import sys, os, json, struct, subprocess, shutil, time, tempfile, atexit
VERSION = '5.5'
YTDLP_PATH = '__YTDLP__'
FFMPEG_PATH = '__FFMPEG__'
_temp_cookie_file = None
def cleanup():
    global _temp_cookie_file
    if _temp_cookie_file and os.path.exists(_temp_cookie_file): os.remove(_temp_cookie_file)
atexit.register(cleanup)
def read_message():
    raw = sys.stdin.buffer.read(4)
    if not raw: return None
    return json.loads(sys.stdin.buffer.read(struct.unpack('I', raw)[0]).decode('utf-8'))
def send_message(msg):
    encoded = json.dumps(msg).encode('utf-8')
    sys.stdout.buffer.write(struct.pack('I', len(encoded)) + encoded)
    sys.stdout.buffer.flush()
def find_tool(name, custom=None):
    paths = [p for p in [custom, YTDLP_PATH if name == 'yt-dlp' else FFMPEG_PATH, shutil.which(name)] if p]
    for p in paths:
        try:
            r = subprocess.run([p, '--version'], capture_output=True, text=True, timeout=10)
            if r.returncode == 0: return {'available': True, 'path': p, 'version': r.stdout.split()[1] if 'yt-dlp' in r.stdout else 'ok'}
        except: pass
    return {'available': False, 'path': None, 'version': None}
def save_cookies(content):
    global _temp_cookie_file
    if not content: return None
    fd, path = tempfile.mkstemp(suffix='.txt', prefix='adhub_')
    with os.fdopen(fd, 'w') as f: f.write(content)
    _temp_cookie_file = path
    return path
def handle_download(msg):
    url, fmt, quality, audio = msg.get('url'), msg.get('format','video'), msg.get('quality','best'), msg.get('audioFormat')
    yt = find_tool('yt-dlp', msg.get('ytdlpPath'))
    if not yt['available']: return {'success': False, 'error': 'yt-dlp neni dostupny'}
    cmd = [yt['path'], '--no-playlist', '--no-warnings', '--ignore-errors', '-o', os.path.expanduser('~/Downloads/%(title).150s.%(ext)s')]
    cookies = save_cookies(msg.get('cookies'))
    if cookies: cmd.extend(['--cookies', cookies])
    if fmt == 'audio' or audio:
        cmd.extend(['-f', 'bestaudio/best'])
        if audio: cmd.extend(['-x', '--audio-format', audio, '--audio-quality', '0'])
        ff = find_tool('ffmpeg', msg.get('ffmpegPath'))
        if ff['available']: cmd.extend(['--ffmpeg-location', os.path.dirname(ff['path'])])
    else:
        cmd.extend(['-f', f'bestvideo[height<={quality}]+bestaudio/best' if quality != 'best' else 'bestvideo+bestaudio/best', '--merge-output-format', 'mp4'])
        ff = find_tool('ffmpeg', msg.get('ffmpegPath'))
        if ff['available']: cmd.extend(['--ffmpeg-location', os.path.dirname(ff['path'])])
    cmd.append(url)
    try:
        r = subprocess.run(cmd, capture_output=True, text=True, timeout=900)
        return {'success': r.returncode == 0, 'error': r.stderr[:200] if r.returncode != 0 else None}
    except Exception as e: return {'success': False, 'error': str(e)[:200]}
def main():
    while True:
        msg = read_message()
        if not msg: break
        action = msg.get('action')
        if action == 'check': send_message({'success': True, 'version': VERSION, 'ytdlp': find_tool('yt-dlp'), 'ffmpeg': find_tool('ffmpeg')})
        elif action == 'test': send_message(find_tool(msg.get('tool'), msg.get('path')))
        elif action == 'download': send_message(handle_download(msg)); break
        elif action == 'ping': send_message({'success': True, 'version': VERSION})
        else: send_message({'success': False, 'error': 'Neznama akce'})
if __name__ == '__main__': main()
PYEOF

sed -i.bak "s|__YTDLP__|$YTDLP|g" "$INSTALL_DIR/native-host/adhub_yt_host.py"
sed -i.bak "s|__FFMPEG__|$FFMPEG_PATH|g" "$INSTALL_DIR/native-host/adhub_yt_host.py"
rm -f "$INSTALL_DIR/native-host/adhub_yt_host.py.bak"
chmod +x "$INSTALL_DIR/native-host/adhub_yt_host.py"

# Manifest
echo '{"name":"com.adhub.ytdownloader","description":"AdHub YouTube Downloader","path":"'"$INSTALL_DIR/native-host/adhub_yt_host.py"'","type":"stdio","allowed_origins":["chrome-extension://*/"]}' > "$INSTALL_DIR/native-host/com.adhub.ytdownloader.json"

# Register
echo -e "\${GREEN}[+]\${NC} Registruji Native Host..."
if [[ "$(uname)" == "Darwin" ]]; then
    CHROME_DIR="$HOME/Library/Application Support/Google/Chrome/NativeMessagingHosts"
else
    CHROME_DIR="$HOME/.config/google-chrome/NativeMessagingHosts"
fi
mkdir -p "$CHROME_DIR"
cp "$INSTALL_DIR/native-host/com.adhub.ytdownloader.json" "$CHROME_DIR/"

echo ""
echo -e "\${GREEN}==============================================\${NC}"
echo -e "\${GREEN}  INSTALACE DOKONCENA!\${NC}"
echo -e "\${GREEN}==============================================\${NC}"
echo ""
echo -e "yt-dlp: \${CYAN}$YTDLP\${NC}"
echo -e "Restartujte prohlizec a otevrete rozsireni."
echo ""
`;
}

// Handler pro generovani instalatoru
function handleGenerateInstaller(platform) {
  try {
    const content = platform === 'windows' ? generateWindowsInstaller() : generateUnixInstaller();
    return { success: true, content: content };
  } catch (e) {
    console.error('[AdHub BG] Chyba pri generovani instalatoru:', e);
    return { success: false, error: e.message };
  }
}
